[package]
name = "fast-hash-index"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
blake3 = "1.5"
clap = { version = "4.5", features = ["derive"] }
globset = "0.4"
rayon = "1.10"
walkdir = "2.5"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
filetime = "0.2"

